name: 'PR Comment Bot Action'
description: 'Checks out the repository and runs an AI analysis on PR changes.'

inputs:
  api_key:
    description: 'API key for the analysis service.'
    required: true
  github_token:
    description: 'GitHub Token for authentication.'
    required: true
  comment_body:
    description: 'The body of the issue comment, if applicable.'
    required: false

outputs:
  comment_status:
    description: 'The status of the comment operation, e.g., "success", "skipped", "failed".'
  comment_message:
    description: 'A brief message describing the outcome of the comment operation.'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Docker image
      shell: bash
      run: docker build -t pr-comment-bot:latest ${{ github.action_path }}

    - name: Run Analysis Container
      id: analysis
      shell: bash
      run: |
        docker run --workdir /github/workspace \
          -v "/github/workspace":"/github/workspace" \
          -e INPUT_API_KEY=${{ inputs.api_key }} \
          -e INPUT_GITHUB_TOKEN=${{ inputs.github_token }} \
          -e INPUT_BASE_SHA=${{ github.event.pull_request.base.sha || github.event.before }} \
          -e INPUT_HEAD_SHA=${{ github.event.pull_request.head.sha || github.event.after }} \
          -e INPUT_COMMENT_BODY='${{ inputs.comment_body }}' \
          pr-comment-bot:latest

    - name: Set action outputs
      shell: bash
      run: |
        echo "comment_status=${{ steps.analysis.outputs.comment_status }}" >> $GITHUB_OUTPUT
        echo "comment_message=${{ steps.analysis.outputs.comment_message }}" >> $GITHUB_OUTPUT