name: 'PR Comment Bot Action'
description: 'Checks out the repository and runs an AI analysis on PR changes.'

inputs:
  api_key:
    description: 'API key for the analysis service.'
    required: true
  github_token:
    description: 'GitHub Token for authentication.'
    required: true
    default: ${{ github.token }}
  comment_body:
    description: 'The body of the issue comment, if applicable.'
    required: false

outputs:
  comment_status:
    description: 'The status of the comment operation, e.g., "success", "skipped", "failed".'
  comment_message:
    description: 'A brief message describing the outcome of the comment operation.'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Analysis Container
      id: analysis
      uses: docker://./
      with:
        api_key: ${{ inputs.api_key }}
        github_token: ${{ inputs.github_token }}
        base_sha: ${{ github.event.pull_request.base.sha || github.event.before }}
        head_sha: ${{ github.event.pull_request.head.sha || github.event.after }}
        comment_body: ${{ inputs.comment_body }}

    - name: Set action outputs
      shell: bash
      run: |
        echo "comment_status=${{ steps.analysis.outputs.comment_status }}" >> $GITHUB_OUTPUT
        echo "comment_message=${{ steps.analysis.outputs.comment_message }}" >> $GITHUB_OUTPUT