name: 'PR Comment Bot Action'
description: 'A GitHub Action to automate commenting on Pull Requests and reacting to issue comments.'

inputs:
  api_key:
    description: 'Your API key for external services that the bot might use.'
    required: true
  github_token:
    description: 'GitHub Token for authentication'
    required: true
  base_sha:
    description: 'The base SHA of the pull request'
    required: false  # Make this optional since it might not always be available
  head_sha:
    description: 'The head SHA of the pull request'
    required: false  # Make this optional since it might not always be available
  comment_body:
    description: 'The body of the issue comment'
    required: false

outputs:
  comment_status:
    description: 'The status of the comment operation, e.g., "success", "skipped", "failed".'
  comment_message:
    description: 'A brief message describing the outcome of the comment operation.'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'message-circle'
  color: 'blue'