# action.yml
name: 'PR Comment Bot'
description: 'Fetches PR diff, gets a summary from an AI service, and posts it as a PR comment.'
author: 'Your Name'

inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'message-square'
  color: 'blue'
