name: Find Changed Files

on:
  pull_request:
    branches:
      - main

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files # Give the step an ID to reference its outputs
        uses: tj-actions/changed-files@v44
        with:
          # This output provides a JSON-formatted string of the array
          json: true

      - name: Echo the changed files
        run: |
          echo "All changed files: ${{ steps.changed_files.outputs.all_changed_files_as_json }}"