# .github/workflows/your-action.yml
name: PR Comment Bot

on:
  # This specifies that the workflow should trigger on pull_request events.
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  Comment-on-PR:
    runs-on: ubuntu-latest

    # This gives the action the necessary permissions to write a comment on the pull request.
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Cache npm packages for faster subsequent runs
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run the PR Comment Bot Script
        # Use npx to execute the TypeScript script directly
        run: npx ts-node ./.github/scripts/pr-comment-bot.ts
        env:
          # Pass secrets and context data as environment variables
          API_KEY: ${{ secrets.API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          COMMENT_BODY: ${{ github.event.comment.body }}
