name: PR Comment Bot

on:
  # This specifies that the workflow should trigger on pull_request events.
  pull_request:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:

jobs:
  Comment-on-PR:
    runs-on: ubuntu-latest

    # This gives the action the necessary permissions to write a comment on the pull request.
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TypeScript
        run: npm install typescript

      - name: Compile TypeScript
        run: npx tsc .github/scripts/pr-comment-bot.ts

      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/scripts/pr-comment-bot.js');
            await script({ github, context });
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}